# Generated by Django 3.1.7 on 2021-03-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_type', models.TextField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], default='foot')),
            ],
            options={
                'db_table': 'courier',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='WorkingHoursRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hours', models.IntegerField()),
                ('start_minutes', models.IntegerField()),
                ('end_hours', models.IntegerField()),
                ('end_minutes', models.IntegerField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='delivery.courier')),
            ],
            options={
                'db_table': 'courier_working_hours',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
                ('assign_time', models.DateTimeField(auto_now_add=True)),
                ('complete_time', models.DateTimeField(null=True)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.courier')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.region')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='DeliveryHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hours', models.IntegerField()),
                ('start_minutes', models.IntegerField()),
                ('end_hours', models.IntegerField()),
                ('end_minutes', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_hours', to='delivery.order')),
            ],
            options={
                'db_table': 'order_delivery_hours',
            },
        ),
        migrations.AddField(
            model_name='courier',
            name='regions',
            field=models.ManyToManyField(db_table='courier_region', to='delivery.Region'),
        ),
    ]
